# Generated by Django 6.0.1 on 2026-01-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='created_by',
        ),
        migrations.AddField(
            model_name='hotel',
            name='location',
            field=models.CharField(default='https://via.placeholder.com/300', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.URLField(default='https://via.placeholder.com/300'),
            preserve_default=False,
        ),
    ]
